services:
  # Redis Service
  - type: redis
    name: laravel-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru

  # Web Service (Laravel App)
  - type: web
    name: laravel-app
    env: php
    plan: starter
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm ci
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: laravel-app
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password
      - key: CACHE_DRIVER
        value: redis
      - key: SESSION_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: redis
      - key: REDIS_HOST
        fromService:
          type: redis
          name: laravel-redis
          property: host
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: laravel-redis
          property: password
      - key: REDIS_PORT
        fromService:
          type: redis
          name: laravel-redis
          property: port
    healthCheckPath: /health

  # Background Worker (Queue Processing)
  - type: worker
    name: laravel-worker
    env: php
    plan: starter
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: php artisan queue:work --verbose --tries=3 --timeout=90
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password
      - key: QUEUE_CONNECTION
        value: redis
      - key: REDIS_HOST
        fromService:
          type: redis
          name: laravel-redis
          property: host
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: laravel-redis
          property: password
      - key: REDIS_PORT
        fromService:
          type: redis
          name: laravel-redis
          property: port

  # Cron Jobs (Task Scheduling)
  - type: cron
    name: laravel-scheduler
    env: php
    plan: starter
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    schedule: "* * * * *"
    startCommand: php artisan schedule:run
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password

databases:
  - name: laravel-db
    databaseName: laravel_production
    user: laravel_user
    plan: starter
